-- MySQL Script generated by MySQL Workbench
-- Sat Sep 16 13:58:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE `mydb`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL UNIQUE,  -- Changed to VARCHAR(255)
  `email` VARCHAR(255) NOT NULL UNIQUE,  -- Changed to VARCHAR(255)
  `phone_num` VARCHAR(255) NOT NULL UNIQUE,  -- Changed to VARCHAR(255)
  `password` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`));
  
-- -----------------------------------------------------
-- Table `mydb`.`Profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Profiles` ;

CREATE TABLE `mydb`.`Profiles` (
  `profile_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `last_name` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `date_of_birth` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `gender` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `blood_type` VARCHAR(255) NOT NULL,  -- Changed to VARCHAR(255)
  `country` VARCHAR(32) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`)
);
  
-- -----------------------------------------------------
-- Table `mydb`.`Tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tokens` ;
    
CREATE TABLE `mydb`.`Tokens` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `refresh_token` VARCHAR(1023), -- Changed to VARCHAR(255)
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`token_id`)
);

-- -----------------------------------------------------
-- Table `mydb`.`Records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Records` ;

CREATE TABLE `mydb`.`Records` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `record_type` VARCHAR(64) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`record_id`))

ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
